name: Build & upload to Firebase App Distribution

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '19.0.1'

      - name: Run corepack enable
        run: corepack enable

      - name: Run yarn install
        run: yarn install

      - name: Run yarn lint
      - run: yarn lint

      
