name: Build & upload to Firebase App Distribution

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "19.0.1"
          cache: "yarn"
          
      - run: corepack enable
      
      - run: yarn install
      
      - run: yarn lint
      
