name: test

on:
  pull_request:
    branches: [master]
jobs:
  job1:
    name: install package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: yarn install
      - run: yarn test
      - run: yarn lint
